### PR TITLE
added a man page

### PR DESCRIPTION
**Pull request by professorjamesmoriarty**
I've made a simple manpage, and added the manpage to the install script.
You can view the manpage with man ./gg.1 , I wanted to add a license line but there
seems to be no license in the project yet. Might I ask why? If you'd like any info added or removed I'd be happy to do adjust.

### CODE REVIEW

**Comment by qw3rtman** [comment]
My bad, I just added the MIT license. Could you add it to the man page?

Thanks for letting me know and thanks for making this! I'll merge it once you add the license. :+1:

**Comment by professorjamesmoriarty** [comment]
MIT info added.

**Comment by qw3rtman** [comment]
Looks good. Thanks! :+1:

**Comment by qw3rtman** [comment]
Moved the man page to its own directory (`man`) to match `gg` being in `bin`.

e266951

**Comment by professorjamesmoriarty** [comment]
Cool stuff, btw you can scratch the manpage off your todo list.

**Comment by qw3rtman** [comment]
Thanks for reminding me! :smile:

**Pull request merged**
