### PR TITLE
Add files status command

### PR DESCRIPTION
**Pull request by maksimf**
It would be nice to have a short command to view project's files status. E.g.: Ohmyzsh has two: `gss` for `git status -s` and `gst` for `git status`.

### CODE REVIEW

**Comment by qw3rtman** [comment]
Running `gg s` displays the files modified in the repository. Does that look like something that would fit under `gg st`?

**Comment by maksimf** [comment]
@qw3rtman Maybe I'm doing something wrong, but if I have changed files and I run `gg s` I get:

```
[master -> origin/master|0f46aa1] Add coverage

position | up-to-date with remote
staging  | not all changes staged (add changes)
commits  | all changes committed
```

It I run `gg st` I get:

```
 M Gemfile
```

`gg s` does not return the actual list of modified files.

**Comment by qw3rtman** [comment]
My bad, didn't realize that `gg s` doesn't show which files have changed.

Instead of creating a new command, what if the files changed was just another section in the output of `gg s`?

**Comment by qw3rtman** [comment]
Added the files changed (unstaged) as a section in `git status`. :+1:

**Pull request closed without merging**
