### PR TITLE
Add a new alias command for filtering logs with a specific file (enhancement)

### PR DESCRIPTION
**Pull request by cosinuz**
Hey,

I like sometimes filtering the logs from git logs by extracting only logs where a certain file has been modified. I added an alias to do so, and some code in the exports.log function to handle this case, and gave the alias 'lf' to do so. I was also thinking of adding the feature that allows to see the diff for a specific file over different recent commits, but that would require more code changes, and I'd be interested to know what you think of it before working on it - if I may work on it :).

Let me know what you think of this one in the meantime!

### CODE REVIEW

**Comment by qw3rtman** [comment]
This is a great addition, thanks for working on it!

I think it'd be better to stick to the same `gg l` or `gg log` command for this instead of creating a new command. If there is a file after the command, it would output the log of that file, otherwise, it would output the entire repositories log.

In addition, this needs to check for the existence of the file and output an error if needed first. I'd recommend running [`fs.open` and looking for an error](https://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback).

Also, there are a couple styling errors, according to Travis CI, so [check those out and get those fixed](https://travis-ci.org/qw3rtman/gg/jobs/54028106).

Let me know what you think about the ideas above. :smile:

**Comment by qw3rtman** [comment]
About the diff suggestion, we would also need to support a basic diff over entire commits, in addition to your suggestion about diffs over a specific file.

If you'd like to work on that, that would be great. Just ensure that you are checking the file exists first, following the style guide, and keep the commands to a minimum (instead of `d` and `df`, just have `d` and check for if there is a file after the command.)

**Comment by cosinuz** [comment]
I basically made the changes you suggested in the new update. I went for fs.openSync instead of fs.open to deal with something more synchronous.
I would be amused to work on the diff feature yeah - I configured my github to have travis CI run on my updates, so it should be checked each time now.
EDIT: hm, still Travis CI error; coding style error from latest updates, regarding indentation. It seems it's been committed this way on the master branch of the main repo. And this merge is not bringing any update though, maybe we should remove it from the pull request?

**Comment by cosinuz** [comment]
@qw3rtman all seems well now, what do you think of it? I'll wait/work for this PR to be merged before moving to the diff implementation :)

**Comment by qw3rtman** [comment]
Looking good. :+1: 

Thanks for the PR!

**Pull request merged**
